### PR TITLE
Update stats command

### LINKED ISSUE #33: create and update statistics command
Create statistics command that will give drivers a breakdown by % of tasks done/not done, types of goods, time of delivery etc..

### PR DESCRIPTION
**Pull request by CSjiade**

### CODE REVIEW

**Comment by pasha-292** [comment]
I think some of the fields in the StatsCommand class need to be changed to private.

**Comment by Jacob-109** [comment]
Could try adding test cases for the stats command to ensure it works well

**Comment by CSjiade** [comment]
> Could try adding test cases for the stats command to ensure it works well

Ok noted will do so asap

**Comment by Jacob-109** [comment]
Looks good, maybe you can try to increase the test coverage further

**Pull request merged**
